# Generated by Django 5.0.6 on 2024-06-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contact_us'},
        ),
    ]
