# Generated by Django 5.0.6 on 2024-06-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cancel',
            new_name='status',
        ),
    ]
