# Generated by Django 5.0.6 on 2024-06-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0002_rename_cancel_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
